CREATE SCHEMA IF NOT EXISTS warehouse_schema;

CREATE TABLE IF NOT EXISTS warehouse_schema.warehouse_item (
    id UUID PRIMARY KEY,
    fragile BOOLEAN NOT NULL,
    width FLOAT NOT NULL,
    height FLOAT NOT NULL,
    depth FLOAT NOT NULL,
    weight FLOAT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS warehouse_schema.warehouse_item_reserved (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    shopping_cart_id UUID NOT NULL,
    product_id UUID NOT NULL,
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity >= 0)
);