DROP TABLE IF EXISTS order_booking;
DROP TABLE IF EXISTS warehouse_item_reserved;
DROP TABLE IF EXISTS warehouse_item;

CREATE TABLE IF NOT EXISTS warehouse_item (
    id UUID PRIMARY KEY,
    fragile BOOLEAN NOT NULL,
    width NUMERIC(9,4) NOT NULL,
    height NUMERIC(9,4) NOT NULL,
    depth NUMERIC(9,4) NOT NULL,
    weight NUMERIC(9,4) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS warehouse_item_reserved (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    shopping_cart_id UUID NOT NULL,
    username VARCHAR(255) NOT NULL,
    product_id UUID NOT NULL,
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS order_booking (
    order_id UUID PRIMARY KEY,
    product_id UUID NOT NULL,
    booked_quantity INTEGER NOT NULL CHECK (booked_quantity >= 0),
    delivery_id UUID,
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES warehouse_item(id)
);